### ISSUE TITLE
Misleading Domination timer

### ISSUE THREAD

**Issue by Picajoluna** [Picajoluna/Walrus-Bugs#10]
The Domination gamemode timer is unclear.  As of now, it shows for instance:`5:8s` -- it isn't entirely clear that this is 5 minutes and 8 seconds.  An alternative could simply be to replace the colon `:` with an `m`.  We could also get rid of the trailing `s`.

**Comment by mattarnold98** [comment]
Are we all happy with this new look? 

<img width="843" alt="Screenshot 2020-03-23 at 11 38 23" src="https://user-images.githubusercontent.com/8415597/77312984-e94d4300-6cfa-11ea-9c9f-e057b6ae1806.png">

**Comment by mattarnold98** [comment]
Should be live on the servers now
